# Use an official Python runtime as the base image
FROM amd64/python:3.9-buster as project_env

# Set the working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    build-essential \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements.txt file
COPY requirements.txt .

# Install Python dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Install TensorFlow with CPU support
RUN pip3 install --no-cache-dir tensorflow-cpu==2.17.0

# Set the environment variable for TensorFlow to use GPU (even though ist not used)
ENV TF_FORCE_GPU_ALLOW_GROWTH=true

# Ensure the CUDA and CUDNN libraries are in the PATH ((even though ist not needed for CPU)
ENV LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
ENV PATH=/usr/local/cuda/bin:$PATH

# Copy the rest of the application code
COPY train_models.py app_config.py .

# Run the training script
CMD ["python3", "train_models.py"]
